server:
  port: 5599
spring:
  application:
    name: @artifactId@
  redis:
    host: livk.com
    password: 123456
  kafka:
    bootstrap-servers: livk.com:9092
  cloud:
    nacos:
      discovery:
        server-addr: livk.com:8848
  boot:
    admin:
      client:
        url: lb://api-monitor
        username: livk
        password: 123456
        instance:
          prefer-ip: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://livk.com:3306/sc_gateway
    username: root
    password: 123456
    hikari:
      schema: classpath:sql/table.sql
  profiles:
    active: @profiles.active@
mybatis-plus:
  global-config:
    banner: false
swagger:
  enable: true
  version: @version@
management:
  endpoints:
    web:
      exposure:
        include: '*'
