server:
  port: 5599

spring:
  application:
    name: api-dynamic
  redis:
    host: livk.com
    password: 123456
  kafka:
    bootstrap-servers: livk.com:9092
  cloud:
    nacos:
      discovery:
        server-addr: livk.com:8848
  boot:
    admin:
      client:
        url: lb://api-monitor
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://livk.com:5432/spring_livk
    username: postgres
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
