server:
  port: 9852

management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: @artifactId@
  redis:
    host: livk.com
    password: 123456
  kafka:
    bootstrap-servers: livk.com:9092
  cloud:
    nacos:
      discovery:
        server-addr: livk.com:8848
  boot:
    admin:
      client:
        url: lb://api-monitor
        username: livk
        password: 123456
  profiles:
    active: @profiles.active@


#logging:
#  level:
#    root: debug
swagger:
  enable: true
